#!/usr/bin/env bash
# install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo nginx
sudo chmod -R 755 /var/www/
echo "Hello World!" > /var/www/html/index.html
sudo nginx -s reload
