#!/usr/bin/env bash
# install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo nginx
sudo chmod -R 755 /var/www/
echo "Hello World!" > /var/www/html/index.html
echo sed -i '25 i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo nginx -s reload
