#!/usr/bin/env bash
# configure a custom header for nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo nginx
sudo chown -R "$USER":"$USER" /var/www
sudo chmod -R 755 /var/www/
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '25 i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i '28 i\\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '28 a\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
