#!/usr/bin/env bash
#install anad configure haproxy
sudo add-apt-repository ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get -y install haproxy

sudo chown -R "$USER":"$USER" /etc/haproxy/

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

echo -e \
'\nfrontend http
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server web1 54.157.143.204:80 check
	server web2 54.236.28.149:80 check' >> /etc/haproxy/haproxy.cfg

sudo chown "$USER":"$USER" /etc/default/haproxy

echo "ENABLED=1" > /etc/default/haproxy

if [[ "$(pgrep -c haproxy)" -eq 0 ]]
then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
