#!/usr/bin/env bash
# fix what is keeping nginx from listening on port 80

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
