#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
#  localhost resolves to 127.0.0.2
#  facebook.com resolves to 8.8.8.8.

cp /etc/hosts /host.new
sed -i s/127.0.0.1/127.0.0.2/ /host.new
echo -e "8.8.8.8  \tfacebook.com" >> /host.new
cp -f /host.new /etc/hosts
